@extends('dashboard.layout.adminmain')
@section('content')
<style>
/* Equal height for all dashboard boxes */
.equal-card {
    display: flex;
}

.dashboard-card {
    height: 100%;
    min-height: 350px;
    border-radius: 14px;
    transition: 0.25s;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}

.dashboard-card:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 22px rgba(0,0,0,0.12);
}

.knob-wrapper {
    position: relative;
    width: 160px;
    height: 160px;
}

.knob-value {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 24px;
    font-weight: 700;
    color: #333;
}

/* hide jquery knob default text */
.knob + input {
    display: none !important;
}
/* HIDE ALL autogenerated knob value inputs */
input.knob + input,
input.knob + canvas + input,
canvas + input,
.knob ~ input[type="text"] {
    display: none !important;
}


</style>


<div class="container-fluid">

    <!-- start page title -->
    <div class="py-3 py-lg-4">
        <div class="row">
            <div class="col-lg-6">
                <h4 class="page-title mb-0">Dashboard</h4>
            </div>
            <div class="col-lg-6">
                <div class="d-none d-lg-block">
                    <ol class="breadcrumb m-0 float-end">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">president</a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- end page title -->

   <div class="row">

@foreach($branches as $branch)

    @php
        $totalMembers = $branch->members_count ?? 0;
        $branchName   = $branch->branch ?? 'Unknown';

        // Percentage calculation
        $totalAll = $branches->sum('members_count');
        $percentage = $totalAll > 0 ? round(($totalMembers / $totalAll) * 100) : 0;

        // Improved color logic
        if ($percentage >= 50) {
            $color = "#28a745"; // green
        } elseif ($percentage >= 20) {
            $color = "#ffc107"; // yellow
        } elseif ($percentage > 0) {
            $color = "#dc3545"; // red
        } else {
            $color = "#6c757d"; // grey for empty branches
        }

        // Correct icon mapping (KEYS checked properly)
        $icons = [
            'Cebu'         => 'fa-store',
            'Main'         => 'fa-building',
            'Head Office'  => 'fa-city',
            'Corp'         => 'fa-industry',
        ];

        $icon = 'fa-store';
        foreach ($icons as $key => $ic) {
            if (stripos($branchName, $key) !== false) {
                $icon = $ic;
                break;
            }
        }

    @endphp

    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 mb-4">
        <div class="card shadow-sm dashboard-card">
            <div class="card-body text-center">

                {{-- Icon --}}
                <i class="fas {{ $icon }}" style="font-size:30px; color: {{ $color }};"></i>

                {{-- Knob --}}
                <div class="knob-wrapper mx-auto mt-2">

                    <input
                        class="knob"
                        data-plugin="knob"
                        data-width="160"
                        data-height="160"
                        data-min="0"
                        data-max="100"
                        data-fgColor="{{ $color }}"
                        data-bgColor="#e9ecef"
                        data-thickness="0.1"
                        data-readOnly="true"
                        value="{{ $percentage }}"
                    />

                    {{-- Text inside circle --}}
                    <div class="knob-value">{{ $percentage }}%</div>

                </div>

                {{-- Branch Name --}}
                <h5 class="mt-3 fw-bold">{{ $branchName }}</h5>

                {{-- Member Count --}}
                <p class="text-muted mb-0"><strong>{{ $totalMembers }}</strong> Members</p>

            </div>
        </div>
    </div>

@endforeach

</div>

    <!-- end row -->


    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">

                    <h4 class="card-title">Recent Customers</h4>
                    <p class="card-subtitle mb-4 font-size-13">Transaction period from 21 July to 25 Aug
                    </p>

                    <div class="table-responsive">
                        <table class="table table-centered table-striped table-nowrap">
                            <thead>
                                <tr>
                                    <th>Card No </th>
                                    <th>Customer</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                    <th>Address</th>
                                    <th>Create Date</th>
                                    <th>Branch</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($recent_members as $member )
                                <tr>
                                    <th>{{$member->card_no}} </th>
                                    <td class="table-user">

                                        <a href="javascript:void(0);"
                                            class="text-body font-weight-semibold">{{$member->name}}</a>
                                    </td>
                                    <td>
                                        {{$member->phone}}
                                    </td>
                                    <td>
                                        {{$member->email}}
                                    </td>
                                    <td>
                                        {{$member->address}}
                                    </td>
                                    <td>
                                        {{$member->created_at->format('Y-m-d')}}
                                    </td>
                                    <td>{{$member->user->branch}} </td>
                                </tr>
                                @endforeach


                            </tbody>
                        </table>
                    </div>

                </div> <!-- end card-body-->
            </div> <!-- end card-->
        </div> <!-- end col -->


        <!-- end row-->

    </div> <!-- container -->





    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                

                   
@endsection